### ISSUE TITLE
Some metrics are lost 

### ISSUE THREAD

**Issue by zihaoyu** [Chatham/statsd-socket.io#7]
This happens when I have a few metrics that share the same prefix, but do not have the same level of namespaces. For example:

```
'counters.token': 100,
'counters.token.200': 80,
'counters.token.401': 15,
'counters.token.500': 5
```

The backend will return:

```
{
  "counters": {
    "tokens: 100
  }
}
```

Is there a generic solution to return all the metrics? I know I can rename the first metric to `counters.token.total`, but there are many metrics in our application, and they are being used in many other monitoring systems and dashboards.

**Comment by chrishoffman** [comment]
I wonder how other backends might support this use case.  The original backend for statsd was Graphite and you can't have a stat name that is both a folder and a metric.  Also, how would you propose modelling this in JSON?
